# Generated by Django 6.1.1 on 2026-09-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_admin_options_alter_kitob_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='ish_vaqti',
            field=models.IntegerField(),
        ),
    ]
